export const REQUEST_MAPPING = 'api/v1';
export const REQUEST_MAPPING_DOCUMENT_TYPE = `${REQUEST_MAPPING}/document-type`;
const REQUEST_MAPPING_TAXPAYER_TYPE = `${REQUEST_MAPPING}/taxpayer-type`;
const REQUEST_MAPPING_SERVICES = `${REQUEST_MAPPING}/services`;

export const USER_API_ENDPOINTS = {
  GET_BY_ID: REQUEST_MAPPING + '/users',
};

export const BUSINESS_API_ENDPOINTS = {
  GET_BY_ID: REQUEST_MAPPING + '/business',
};

export const LOGIN_API_ENDPOINTS = {
  REQUEST_MAPPING: 'auth',
  LOGIN: 'login',
}

export const DOCUMENTS_API_ENDPOINTS = {
  FIND_ALL: `${REQUEST_MAPPING_DOCUMENT_TYPE}/documents`,
  FIND_BY_ID: REQUEST_MAPPING_DOCUMENT_TYPE,
  CREATE: `${REQUEST_MAPPING_DOCUMENT_TYPE}/create`,
  UPDATE: `${REQUEST_MAPPING_DOCUMENT_TYPE}/update`,
  DELETE: `${REQUEST_MAPPING_DOCUMENT_TYPE}/delete`,
}

export const TAXPAYER_API_ENDPOINTS = {
  FIND_ALL: REQUEST_MAPPING_TAXPAYER_TYPE,
  FIN_ALL_TAXPAYER_NAMES: REQUEST_MAPPING_TAXPAYER_TYPE + '/get-all-client-names',
  FIND_BY_ID: REQUEST_MAPPING_TAXPAYER_TYPE,
  CREATE: REQUEST_MAPPING_TAXPAYER_TYPE + '/create',
  UPDATE: REQUEST_MAPPING_TAXPAYER_TYPE + '/update',
  DELETE: REQUEST_MAPPING_TAXPAYER_TYPE + '/delete',
}

export const SERVICE_API_ENDPOINTS = {
  FIND_ALL: REQUEST_MAPPING_SERVICES,
  FIN_ALL_TO_EXPORT_TO_CSV: REQUEST_MAPPING_SERVICES + '/export-to-csv',
  FIND_ALL_BY_USER: REQUEST_MAPPING_SERVICES + '/user',
  FIND_BY_ID: REQUEST_MAPPING_SERVICES,
  FIND_BASIC_BY_ID: REQUEST_MAPPING_SERVICES + '/basic',
  FIND_DETAILS_BY_ID: REQUEST_MAPPING_SERVICES + '/details',
  CREATE: REQUEST_MAPPING_SERVICES + '/new-service',
  UPDATE: REQUEST_MAPPING_SERVICES + '/update',
  UPDATE_MAIN_DATA: REQUEST_MAPPING_SERVICES + '/update-main-service-data',
  UPDATE_SECONDARY_DATA: REQUEST_MAPPING_SERVICES + '/update-secondary-service-data',
  UPDATE_SINGLE_SECONDARY_DATA: REQUEST_MAPPING_SERVICES + '/update-single-secondary-service',
  UPDATE_SERVICE_STATE: REQUEST_MAPPING_SERVICES + '/update-service-state',
  UPDATE_SERVICE_DISABLE: REQUEST_MAPPING_SERVICES + '/update-service-disable',
  DELETE: REQUEST_MAPPING_SERVICES + '/delete',
  NEXT_SERVICE_NUMBER: REQUEST_MAPPING_SERVICES + '/next-service-number',
  TRAILERS: REQUEST_MAPPING_SERVICES + '/trailers',
  COMPANY_NAME_BY_LICENSE_PLATE: REQUEST_MAPPING_SERVICES + '/company-name',
  COLLABORATORS: REQUEST_MAPPING_SERVICES + '/collaborators',
  SERVICE_ID_AND_NUMBER_BY_BUSINESS: REQUEST_MAPPING_SERVICES + '/business',
  SERVICE_ID_FOR_EXPENSES: REQUEST_MAPPING_SERVICES + '/service-expenses',
  SERVICE_ID_NUMBERS_BY_EXPENSES: REQUEST_MAPPING_SERVICES + '/find-services-for-expenses',
  GET_PREVIOUS_SERVICE_ID_AND_NUMBER: REQUEST_MAPPING_SERVICES + '/previous-ids-and-numbers',
  GET_SUBCLIENTS_BY_CLIENT: REQUEST_MAPPING_TAXPAYER_TYPE + '/get-sub-client',
  GET_SERVICE_ID_AND_NUMBER_FOR_COLLABORATOR: REQUEST_MAPPING_SERVICES + '/find-services-for-collaborators',
  GET_PREVIOUS_SERVICE_ID_AND_NUMBER_FOR_COLLABORATOR: REQUEST_MAPPING_SERVICES + '/find-previous-services-for-collaborators',
  GET_SERVICE_DETAILS_BY_SERVICE_NUMBER: REQUEST_MAPPING_SERVICES + '/details/serviceNumber',
}
