export const REQUEST_MAPPING = 'api/v1';
export const REQUEST_MAPPING_DOCUMENT_TYPE = `${REQUEST_MAPPING}/document-type`;
const REQUEST_MAPPING_TAXPAYER_TYPE = `${REQUEST_MAPPING}/taxpayer-type`;
const REQUEST_MAPPING_SERVICES = `${REQUEST_MAPPING}/services`;

export const USER_API_ENDPOINTS = {
  GET_BY_ID: REQUEST_MAPPING + '/users',
};

export const BUSINESS_API_ENDPOINTS = {
  GET_BY_ID: REQUEST_MAPPING + '/business',
};

export const LOGIN_API_ENDPOINTS = {
  REQUEST_MAPPING: 'auth',
  LOGIN: 'login',
};

export const DOCUMENTS_API_ENDPOINTS = {
  FIND_ALL: `${REQUEST_MAPPING_DOCUMENT_TYPE}/documents`,
  FIND_BY_ID: REQUEST_MAPPING_DOCUMENT_TYPE,
  CREATE: `${REQUEST_MAPPING_DOCUMENT_TYPE}/create`,
  UPDATE: `${REQUEST_MAPPING_DOCUMENT_TYPE}/update`,
  DELETE: `${REQUEST_MAPPING_DOCUMENT_TYPE}/delete`,
};

export const TAXPAYER_API_ENDPOINTS = {
  FIND_ALL: REQUEST_MAPPING_TAXPAYER_TYPE + '/taxpayer-types',
  FIN_ALL_TAXPAYER_NAMES:
    REQUEST_MAPPING_TAXPAYER_TYPE + '/get-all-client-names',
  FIND_BY_ID: REQUEST_MAPPING_TAXPAYER_TYPE,
  CREATE: REQUEST_MAPPING_TAXPAYER_TYPE + '/create',
  UPDATE: REQUEST_MAPPING_TAXPAYER_TYPE + '/update',
  DELETE: REQUEST_MAPPING_TAXPAYER_TYPE + '/delete',
};

export const SERVICE_API_ENDPOINTS = {
  
};
